# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "128f1df9c644a9b246f9cf53e87c0a7e"
name = "shop"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]
